Do not use SimpleDateFormat format "z"
java.test.SimpleDateFormat does not have clear rules for format "z".
The rule:
z 	Time zone 	General time zone 	Pacific Standard Time; PST; GMT-08:00
General time zone: Time zones are interpreted as text if they have names

https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/text/SimpleDateFormat.html#timezone

Avoid using SimpleDateFormat format "z" when not necessary.

Example of errors detected:
[ERROR] Failures:
[ERROR]   TestPureDate.testFormatWithTimeZoneShift:52 expected:<...-12-31 19:01:01.070 [CST]> but was:<...-12-31 19:01:01.070 [GMT-06:00]>